settings:
  title: 'Status Page'
  url: 'https://status.incunabula.be' # used for Slack message
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON location

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: tatooine-incunabula-be # unique identifier
    name: tatooine.incunabula.be
    description: 'Running on a Raspberry Pi 5 (Loppem)' # default=empty
    url: 'https://tatooine.incunabula.be/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-incunabula-be
    name: www.incunabula.be
    description: 'Serverless with Cloudflare Pages'
    url: 'https://www.incunabula.be'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-incunabula-be
    name: Jekyll blog on Github Pages
    url: 'https://blog.incunabula.be/'
    method: GET
    expectStatus: 200
